### ISSUE TITLE
Crashing issue on PTDE

### ISSUE THREAD

**Issue by Stagmattica** [metal-crow/Dark-Souls-1-Overhaul#11]
The Dark Souls Overlay mod, chainloaded with DSPV, causes the game to crash after loading the character and moving a few steps. Doesn't crash if the character stands still.
Various texture overrides in place, using DSFix. Dark Souls Input Customizer running in conjunction with DSFix (chainloaded DINPUT). Also running InfernoPlus's Dark Souls Remastest mod and DSCM. 
Latest version of Dark Souls PTDE, on Windows 10 20H2.

EDIT: Using Spacewar build.

**Comment by metal-crow** [comment]
DSPV? Googling that didn't turn up anything

**Comment by SeanPesce** [comment]
I believe this is a compatibility issue between the Overhaul's XInput hooks and Dark Souls Input Customizer. Unfortunately IIRC the Overhaul's XInput hooks are hard-coded (due to the use of XInput for navigating the multi-save menu). It probably wouldn't be too hard to add an absolute XInput toggle, but I don't want to promise anything as I have a lot of commitments at the moment.

**Comment by metal-crow** [comment]
i can do that really quick actually

**Comment by metal-crow** [comment]
No, Dark Souls Input Customizer seems to work fine with the overhaul, just tested. Plus i think others have used it with it before with no issues. What is DSPV @Stagmattica ?

**Comment by metal-crow** [comment]
Update: DSPV is pvp watchdog. which makes things hard since that's closed source.

**Comment by SeanPesce** [comment]
That's weird, I was using Watchdog most of the time when I was testing. @metal-crow were you able to reproduce the crash?

**Comment by metal-crow** [comment]
I haven't tried yet, i'll check it out once i've finished up some other urgent stuff

**Comment by metal-crow** [comment]
nope, watchdog works fine for me with the overhaul and DSCM loaded. So not sure what's up. @Stagmattica can you provide any more info about the crash? You had watchdog chained through the overhaul.ini option, right?

**Comment by metal-crow** [comment]
maybe it's a conflict between the input customizer AND watchdog AND the overhaul? lemme test

**Comment by metal-crow** [comment]
nope, that's not it either. I'm running fine with the overhaul, input customizer, watchdog, dsfix, and DSCM all loaded. Which honestly i'm amazed it all works tbh, but no problems on my end.

**Comment by metal-crow** [comment]
Update from Stag:
also, hey metalcrow, i looked into the issue on my end again and it turned out to have something to do with my save. the bug occurend on one character, the others worked fine.
i don't know how that happened, i deleted the save i had before installing remastest

so we're all good
