### ISSUE TITLE
Got Banned for using it

### ISSUE THREAD

**Issue by Bobernot** [metal-crow/Dark-Souls-1-Overhaul#16]
Only mod or 3rd party source I used within a couple weeks, got banned. It might have to do with I went to an area that I hadn't unlocked, but that would be weird. If this is a problem would probably put it somewhere.

**Comment by metal-crow** [comment]
Ok, you're the 2nd person that has reported getting banned in the last 24 hours. I'm REALLY sorry about that, i thought i tested everything but apparently i missed something.

The newest beta6 i pushed out yesterday has even more anti-ban countermeasures added to it, which should hopefully fix this issue. But at the moment i don't know, exactly, what triggers the game to ban. I'm rapidly trying to test stuff.

If you would like to join the discord (https://discord.gg/nABqj8G) it might be easier to communicate there. But for right now, the best advice i can give is upgrade to beta6, and you can get unbanned once if you follow https://service-en.bandainamcoent.eu/app/detail/a_id/2309/p/6856 and submit a ticket at https://support.bandainamcoent.com/hc/en-us/requests/new
