### ISSUE TITLE
Pressing F5 to switch between legacy or overhaul doesn't work

### ISSUE THREAD

**Issue by X2TheTap** [metal-crow/Dark-Souls-1-Overhaul#18]
Playing on beta16, DSR

**Comment by metal-crow** [comment]
Sorry about that! Known bug, i forgot to include the right version of the ini with this release. Use this 
[d3d11_mod.ini.txt](https://github.com/metal-crow/Dark-Souls-1-Overhaul/files/10963642/d3d11_mod.ini.txt)
in the meantime, i'll have it fixed next release.
