### ISSUE TITLE
Can't get the searching red eye orb

### ISSUE THREAD

**Issue by Zanjitku** [metal-crow/Dark-Souls-1-Overhaul#19]
in the description it says Rickert sells it but i check him and he doesn't sell it.

**Comment by metal-crow** [comment]
Can you check the output on the console that pops up on boot? Does it report any errors, such as inability to find files? You may have not copied in the overhaul folder.

**Comment by Zanjitku** [comment]
ok i see ERROR: The file ".\overhaul\c0000.anibnd.dcx" could not be found. Using default files instead. in the console could that be it?

**Comment by metal-crow** [comment]
yep! That'll do it, you are missing the overhaul folder in the DSR folder. You need to copy that in.

**Comment by Zanjitku** [comment]
Yeah its working now, thanks for the help.
